package main

APP_NAME :: "GOL - GenSim"

WINDOW_WIDTH :: 800
WINDOW_HEIGHT :: 600

CELL_SIZE :: 10

GRID_WIDTH :: WINDOW_WIDTH / CELL_SIZE
GRID_HEIGHT :: WINDOW_HEIGHT / CELL_SIZE


INITIAL_GENOME_COUNT :: 10
INITIAL_COVERAGE :: .1

MUTATION_TRIGGER :: 128


EMPTY_TO_RESOURCE_NEIGHBOR_TRIGGER :: 8
RESOURCE_TO_GRAZER_NEIGHBOR_TRIGGER :: 8
GRAZER_TO_PREDATOR_NEIGHBOR_TRIGGER :: 8
